### ISSUE TITLE
Google Map API for ALPS

### ISSUE THREAD

**Issue by hans-olson** [adventistchurch/alps-gutenberg-blocks#112]
We found a Google API key that is supposedly for ALPS. @YauheniKapliarchuk or @designerbrent do you have any knowledge of what this is supposed to do for us? Can we remove it?

**Comment by YauheniKapliarchuk** [comment]
Hi @hans-olson ,

I did some investigation in our infrastructure of ALPS (theme and blocks) and didn't find any places where we can use Google API key.

Of course, I can't check some servers/services sides, because I don't have access to this. 
I think, you can check Cloudflare side and repos variables sides to be sure we are not using this key 100%.

Thanks,
Best Regards!
