### ISSUE TITLE
Duplicated Styles in Compiled CSS

### ISSUE THREAD

**Issue by designerbrent** [adventistchurch/alps-gutenberg-blocks#68]
With the way the code is currently getting compiled, `blocks.editor.build.css` and `blocks.style.build.css` are duplicated 15-16 times for each files. 

We need to work on the compilation process to prevent this from happening.

**Comment by YauheniKapliarchuk** [comment]
Hi everyone,

1. This issue was checked on the **_guthenberg_** blocks side;
2. This issue was checked on the **_ALPS theme_** side;
3. This issue was checked on the **_browser_** side;
4. This issue was checked **_rendering styles_** side;

Unfortunately I can't reproduce this issue.

@hans-olson @designerbrent Could you please support me on this investigation?

Thanks,
Best Regards!

CC: @daniel-eesti @johnrbeckett
