### ISSUE TITLE
"register_rest_route" error

### ISSUE THREAD

**Issue by dburry** [adventistchurch/alps-gutenberg-blocks#72]
On my test machine, when I go to a page and edit it... momentarily I see the following error message:

<img width="1440" alt="Screen Shot 2021-06-17 at 15 33 35" src="https://user-images.githubusercontent.com/180868/122480439-b9363380-cf81-11eb-893c-721cfbba4f17.png">
and then after 1 second I see the normal edit screen.

Also, when I go to change the parent here I see the same error in a response header field (numbered arrows are steps to reproduce it):
<img width="1440" alt="Screen Shot 2021-06-17 at 15 47 59" src="https://user-images.githubusercontent.com/180868/122482127-cf91be80-cf84-11eb-96b1-b3cbe34aa4d8.png">

Note that both calls listed that go to "/index.php?rest_route=/wp/v2/pages*" have this error.

Now on the https://www.adventist.org site, the call to /wp-json/wp/v2/pages* actually becomes a 500 error additionally:
<img width="1440" alt="Screen Shot 2021-06-17 at 16 03 15" src="https://user-images.githubusercontent.com/180868/122482559-a6bdf900-cf85-11eb-9da3-59ca88161d39.png">
(it also has this error message present in a response header, though it's not shown in this screenshot)

I have looked at the php debug and wp debug settings and so far have been unable to get any further error message from the 500 error...

**Comment by designerbrent** [comment]
Here is the error that Wordpress returns: 

`x-wp-doingitwrong | register_rest_route  (since 5.5.0; The REST API route definition for  &lt;code&gt;alps-gutenberg-blocks/latest-posts/tags&lt;/code&gt; is  missing the required &lt;code&gt;permission_callback&lt;/code&gt;  argument. For REST API routes that are intended to be public, use  &lt;code&gt;__return_true&lt;/code&gt; as the permission callback.)
-- | --
`

**Comment by YauheniKapliarchuk** [comment]
https://www.adventist.org/wp-json/wp/v2/pages?per_page=100&exclude=32029&parent_exclude=32029&orderby=menu_order&order=asc&co
ntext=edit&_locale=user

**Comment by dburry** [comment]
the full url on adventist.org for this specific error is:

https://www.adventist.org/wp-json/wp/v2/pages?per_page=100&exclude=32029&parent_exclude=32029&orderby=menu_order&order=asc&context=edit&_locale=user

**Comment by dburry** [comment]
here is where I found the call to `register_rest_route` within the alps-gutenberg-blocks code:

```
adventist@web05:/www/www.adventist.org/public_html/wp-content/plugins/alps-gutenberg-blocks$ grep -rn register_rest_route .
./src/blocks/latest-posts/block.php:90:        register_rest_route( 'alps-gutenberg-blocks', '/latest-posts/tags', [
```

**Comment by dburry** [comment]
here I found an explanation for this error:

https://make.wordpress.org/core/2020/07/22/rest-api-changes-in-wordpress-5-5/ search for the word "doing" and you will see the explanation.

**Comment by designerbrent** [comment]
A quick update: Late last week we found the blame for the error preventing the changing of the page was a different plugin. That said, I would still like to make sure that this warning gets resolved so we are more prepared moving forward.

**Comment by YauheniKapliarchuk** [comment]
After some investigation we decided:

- Run this version of the ALPS and guthenberg blocks;
- Test it on the QA env;

After that test to continue or finish.

Thanks,
Best Regards!

CC: @hans-olson  @daniel-eesti  @johnrbeckett @designerbrent

**Comment by YauheniKapliarchuk** [comment]
Hello everyone.

At the moment, I have checked this case on my local investment. I also checked the production staging. The main reason was not updated plugins, I made the necessary updates and this problem was fixed. Please let us know if it appears again and how to reproduce it.


![Screenshot 2022-10-10 at 19.39.16.png](https://images.zenhubusercontent.com/5fad62a4ad9b1d5fdb82c9f8/a1f968a5-85ce-4d9d-b8e8-691f230594af)

@designerbrent also I checked the request from ALPS Guthenberg Blocks and now it works correct on my local env and prod staging.

@daniel-eesti  @hans-olson Could you please check it on your side?

Thanks,
Best Regards!

CC: @designerbrent @dburry @johnrbeckett

**Comment by daniel-eesti** [comment]
@YauheniKapliarchuk  I've tested it and I have no error

![telegram-cloud-photo-size-2-5348301304176427060-y](https://user-images.githubusercontent.com/98831022/195344278-06369add-0ce3-40dd-91c0-d72695dff600.jpg)
